---
# Source: elasticsearch/templates/elasticsearch/master/service.yaml
kind:           Service
apiVersion:     v1
metadata:
    name:       maestro-service
spec:
    ports:
        - name: serving
          port: 9200
          targetPort: 9200
        - name: nodo
          port: 9300
          targetPort: 9300
    selector:
        app: maestro
    type: ClusterIP
---
# Source: elasticsearch/templates/elasticsearch/master/statefulset.yaml
kind:           StatefulSet
apiVersion:     apps/v1
metadata:
    name:       RELEASE-NAME-maestro

spec:
    replicas: 3
    
    selector:
        matchLabels:
            app: RELEASE-NAME-maestro

    serviceName: RELEASE-NAME-maestro
    
    template:
        metadata:
            labels:
                app: RELEASE-NAME-maestro            
        spec:
            containers:
                - name:     maestro-contenedor
                  
                  image:    docker.elastic.co/elasticsearch/elasticsearch:7.12.0 
                  
                  ports:
                    - containerPort: 9300
                    - containerPort: 9200
                  env:
                    - name: node.name
                      valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                    - name: cluster.name
                      value: "MiCluster"
                    - name: discovery.seed_hosts
                      value: "maestro-statefulset-0.maestro-service,maestro-statefulset-1.maestro-service,maestro-statefulset-2.maestro-service"
                    - name: cluster.initial_master_nodes
                      value: "maestro-statefulset-0,maestro-statefulset-1,maestro-statefulset-2"
                    - name: ES_JAVA_OPTS
                      value: "-Xms220m -Xmx220m"
                    - name: node.master
                      value: "true"
                    - name: node.voting_only
                      value: "false"
                    - name: node.data
                      value: "false"
                    - name: node.remote_cluster_client
                      value: "false"
                  volumeMounts:
                    - name: datos-maestro
                      mountPath: /usr/share/elasticsearch/data
    # Plantilla de peticion de Volumen Persistente para los datos Maestro
    volumeClaimTemplates:
        - metadata:
            name: datos-maestro
          spec:
            storageClassName: volumen-nfs
            resources:
                requests:
                    storage: 10Gi 
            accessModes:
                - ReadWriteOnce
