
kind: Secret
apiVersion: v1

metadata:
    name:  {{ .Release.Name }}-elastic-password
    
data:
    ELASTIC_PASSWORD: {{ .Values.elasticsearch.elasticPassword | default (randAlphaNum 20 )  | b64enc}}