kind:           Service
apiVersion:     v1
metadata:
    name:       maestro-service
spec:
    ports:
        - name: serving
          port: 9200
          targetPort: 9200
        - name: nodo
          port: 9300
          targetPort: 9300
    selector:
        app: maestro
    type: ClusterIP