kind:           StatefulSet
apiVersion:     apps/v1
metadata:
    name:       {{ .Release.Name }}-maestro

spec:

    #{{ if not .Values.elasticsearch.master.replicas -}}
    #{{- fail "Que no has pasado el numero de replicas, pringao !!!!: FALTA el parametro elasticsearch.replicas" }}
    #{{- else -}}
    #replicas: {{ .Values.elasticsearch.master.replicas }}
    #{{- end }}
    
    #replicas: {{ .Values.elasticsearch.master.replicas | default 3 }}
    
    {{- if ne (typeOf .Values.elasticsearch.master.replicas) "float64" }}
    {{- fail "El numero de replicas debe ser un NUMERO pero ENTERO !! PRIINGAO !!!!" }}
    {{- end }}

    {{- if ne (.Values.elasticsearch.master.replicas | int | float64) .Values.elasticsearch.master.replicas }}
    {{- fail "El numero de replicas debe ser un NUMERO pero ENTERO !! PRIINGAO !!!!" }}
    {{- end }}
    
    {{- if not (ge (.Values.elasticsearch.master.replicas |int ) 0 )}}
    {{- fail "El numero de replicas debe ser un NUMERO pero ENTERO POSITIVO !! PRIINGAO !!!!" }}
    {{- end }}
    
    # if eq DATO VALOR  # gt lt ge le ne
    
    replicas: {{ .Values.elasticsearch.master.replicas | required "Que no has pasado el numero de replicas, pringao !!!!: FALTA el parametro elasticsearch.master.replicas"}}
    
    selector:
        matchLabels:
            app: {{ .Release.Name }}-maestro

    {{ $nombreservicio := include "elasticsearch.masterservicename" . -}} 
    serviceName: {{ $nombreservicio }} 

    template:
        metadata:
            labels:
                app: {{ .Release.Name }}-maestro            
        spec:
            containers:
                - name:     maestro-contenedor
                  
                  {{ include "elasticsearch.image" . }}
                  
                  ports:
                    - containerPort: {{ .Values.elasticsearch.service.interno }}
                    - containerPort: {{ .Values.elasticsearch.service.externo }}
                  env:
                    - name: node.name
                      valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                    - name: cluster.name
                      value: "MiCluster"
                    - name: discovery.seed_hosts
                      value: "maestro-statefulset-0.{{ $nombreservicio }} ,maestro-statefulset-1.{{ $nombreservicio }} ,maestro-statefulset-2.{{ $nombreservicio }} "
                    - name: cluster.initial_master_nodes
                      value: "maestro-statefulset-0,maestro-statefulset-1,maestro-statefulset-2"
                    - name: ES_JAVA_OPTS
                      value: "-Xms220m -Xmx220m"
                    - name: node.master
                      value: "true"
                    - name: node.voting_only
                      value: "false"
                    - name: node.data
                      value: "false"
                    - name: node.remote_cluster_client
                      value: "false"
                  volumeMounts:
                    - name: datos-maestro
                      mountPath: /usr/share/elasticsearch/data
    # Plantilla de peticion de Volumen Persistente para los datos Maestro
    volumeClaimTemplates:
        - metadata:
            name: datos-maestro
          spec:
            storageClassName: volumen-nfs
            resources:
                requests:
                    storage: 10Gi 
            accessModes:
                - ReadWriteOnce