elasticsearch:
  image:
    repo: docker.elastic.co/elasticsearch/elasticsearch
    #tag:  7.12.1
  
  #elasticPassword: password
  #elasticPasswordSecret: elastic-password-secret
  
  service:
    interno: 9300
    externo: 9200
  
  customEnvVars: {}
    #ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    #Var2: value2

  master:
    replicas: 3
    
    service:
      customSuffix: maestro
      customName: ""
      
    persistence:
      enabled: true
      # Si activas la persistencia, DEBES informar los siguientes campos:
      
      storageClass: cluster-nfs
      storageCapacity: 10Gi
      accessMode: ReadWriteOnce
      
    customEnvVars: {}
      # ES_JAVA_OPTS: "-Xms220m -Xmx220m"
  data:
    replicas: 2

kibana: ~