elasticsearch:
  image:
    repo: docker.elastic.co/elasticsearch/elasticsearch
    #tag:  7.12.1
  
  service:
    interno: 9300
    externo: 9200
  
  master:
    replicas: 3
    
    service:
      customSuffix: maestro
      customName: ""
      
    persistence:
      enable: true
      # Si activas la persistencia, DEBES informar los siguientes campos:
      #storageClass:
      #storageCapacity:
      #accessMode:
    
  data:
    replicas: 2

kibana: ~